# Generated by Django 5.1 on 2024-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato')], max_length=10)),
                ('status', models.CharField(choices=[('adopted', 'Adoptado'), ('available', 'Disponible para adopción'), ('pending', 'En espera de adopción')], default='available', max_length=10)),
            ],
        ),
    ]
