# Generated by Django 5.1 on 2024-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('adopted', 'Adopted'), ('available', 'Available for adoption'), ('pending', 'Pending adoption')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10),
        ),
    ]
