# Generated by Django 5.1 on 2024-08-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_shelteruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelterUser',
        ),
    ]
