# Generated by Django 5.1 on 2024-08-19 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_adoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to=settings.AUTH_USER_MODEL),
        ),
    ]
